# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

git_config: &git_config
  name: configure git bot
  command: |
      git config user.name "$GITHUB_BOT_USERNAME"
      git config user.email "$GITHUB_BOT_EMAIL"

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/code

jobs:
  dependencies:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  build:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew build
      - run:
          name: Report build failure
          when: on_fail
          command: |
            curl --header "Content-Type: application/json" --request POST \
             --data '{"text":"❌ java-bot-sdk build failed: '${CIRCLE_BUILD_URL}'"}' \
              $DIALOG_HOOK_URL
  release:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          <<: *git_config
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Change origin to push by bot
          command: |
            git remote set-url origin https://${GITHUB_BOT_TOKEN}@github.com/dialogs/java-bot-sdk.git
      - run:
          name: Release
          command: echo -ne '\n\n' | ./gradlew release
      - run:
          name: Report build failure
          when: on_fail
          command: |
            curl --header "Content-Type: application/json" --request POST \
             --data '{"text":"❌ java-bot-sdk release failed: '${CIRCLE_BUILD_URL}'"}' \
              $DIALOG_HOOK_URL
      - run:
          name: Report success
          command: |
            curl --header "Content-Type: application/json" --request POST \
             --data '{"text":"java-bot-sdk release successful! Check it here: '${ARTIFACT_URL}' "}' \
              $DIALOG_HOOK_URL
workflows:
  version: 2
  java-build-release:
    jobs:
      - dependencies     
      - build:
          requires:
            - dependencies
      - release:
          requires:
            - build
          filters:
            branches:
              only: master